[package]
name = "app"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
models = { path = "../models" }
sea-orm = { workspace = true }
fake = { workspace = true }
bcrypt = { workspace = true }
