name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy, llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      # Run cargo build and cargo check
      - run: cargo build --no-default-features && cargo check --no-default-features
        if: matrix.os == 'windows-latest'
      - run: cargo build && cargo check
        if: matrix.os != 'windows-latest'

      # Run cargo fmt and cargo clippy
      - run: cargo fmt --check && cargo clippy --no-default-features -- -D warnings
        if: matrix.os == 'windows-latest'
      - run: cargo fmt --check && cargo clippy -- -D warnings
        if: matrix.os != 'windows-latest'